"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TarjetaDeCredito_1 = require("./TarjetaDeCredito");
var TransferenciaBancaria_1 = require("./TransferenciaBancaria");
var MercadoPago_1 = require("./MercadoPago");
var visa = new TarjetaDeCredito_1.TarjetaDeCredito(122345567889);
var palomaGatoAvena = new MercadoPago_1.MercadoPago("paloma.gato.avena", 2500);
var bip = new TransferenciaBancaria_1.TransferenciaBancaria(200030055556, 30000);
visa.cancelarPago();
visa.procesarPago();
visa.generarRecibo();
console.log("---------------------------------------");
palomaGatoAvena.cancelarPago();
palomaGatoAvena.procesarPago();
palomaGatoAvena.generarRecibo();
console.log("---------------------------------------");
bip.cancelarPago();
bip.procesarPago();
bip.generarRecibo();
