"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var telefonoConCamara_1 = require("./telefonoConCamara");
var telefonoConRadio_1 = require("./telefonoConRadio");
var motorola = new telefonoConCamara_1.TelefonoConCamara("Motorola", false, 100);
var samsung = new telefonoConCamara_1.TelefonoConCamara("Motorola", true, 5);
var nokia = new telefonoConRadio_1.TelefonoConRadio("Nokia", true, 84, 97.3);
samsung.sacarFoto();
motorola.sacarFoto();
motorola.hacerLlamada(2983418803);
motorola.mandarMensaje("Hola, ya estoy yendo");
motorola.encenderApagar();
motorola.hacerLlamada(2983418803);
motorola.mandarMensaje("Hola, ya estoy yendo");
motorola.sacarFoto();
nokia.verFrecuenciaActual();
nokia.mandarMensaje("Hola mundo, si, somos re originales los informaticos");
nokia.hacerLlamada(29135468);
nokia.encenderApagar();
nokia.hacerLlamada(29135468);
nokia.mandarMensaje("Hola mundo, si, somos re originales los informaticos");
nokia.verFrecuenciaActual();
