import { Escuela } from "./Escuela";
import { Profesor } from "./Profesor";
import { Alumno } from "./Alumno";
import { Curso } from "./Curso";

let cresta = new Escuela("CRESTA");

let pintura = new Curso("Pintura",cresta);
let alfareria = new Curso("Alfareria",cresta);
let fotografia = new Curso("Fotografia",cresta);

let maria = new Profesor("Garcia","Maria",25789456,pintura);
let rafa = new Profesor("Rafa","Ela",27486153,alfareria);

let bruno = new Alumno("Bruno","Nosehablade",31759153,pintura);
let agus = new Alumno("Agus","Tina",33005486,pintura);
let pame = new Alumno("Mara","Donna",34884631,pintura);
let max = new Alumno("Max","Verstappen",35675778,alfareria);
let alex = new Alumno("Alex","Albon",34551662,alfareria);
let oscar = new Alumno("Oscar","Piastri",35446113,alfareria);
let kimi = new Alumno("Kimi","Raikkonen",29578796,alfareria);
let frida = new Alumno("Frida","Khalo",3306568,fotografia);

let baseAlumn =[bruno,agus,pame,max,alex,kimi];
cresta.altaCurso(pintura);
cresta.altaCurso(alfareria);
cresta.contratarProfesor(maria);
cresta.contratarProfesor(rafa);
cresta.matricularAlumno(oscar);
cresta.matricularAlumnos(baseAlumn);
cresta.matricularAlumno(kimi);
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se muestra toda la informacion inicial de la institucion");
cresta.mostrarInfo();
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se muestra toda la informacion inicial del curso Pintura");
pintura.mostrarInfo();
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se muestra toda la informacion inicial del curso Alfareria");
alfareria.mostrarInfo();
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se da de alta el curso de Fotografia");
cresta.altaCurso(fotografia);
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se matricula un nuevo alumno, Frida");
cresta.matricularAlumno(frida);
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se muestra toda la informacion inicial del curso Fotografia");
fotografia.mostrarInfo();
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se listan todos los cursos de la institucion");
cresta.getCursos();
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se crea un profesor para Fotografia y se lo contrata");
let manu = new Profesor("Manu","Ela",29228778,fotografia);
cresta.contratarProfesor(manu);
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se despide un profesor, Maria, del curso de Pintura y se muestra la informacion de Pintura");
cresta.despedirProfesor(maria);
pintura.mostrarInfo();
console.log("----------------------------------------------------\n----------------------------------------------------");
console.log("Se da de baja el curso de alfareria y se muestra la informacion de la insstitucion");
cresta.bajaCurso(alfareria);
cresta.mostrarInfo();
console.log("----------------------------------------------------\n----------------------------------------------------");
